name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: LaTeX linter
      # You may pin to the exact commit or the version.
      # uses: colinaaa/chktex-action@5dda098b973d69cdc61ace93fa7bfcef39efaade
      uses: colinaaa/chktex-action@v1.1.2
    - name: LaTeX Action
      # You may pin to the exact commit or the version.
      # uses: fudan-mse/latex-action@eb2eb7ba472011213ac0a6286fd776494623362c
      uses: fudan-mse/latex-action@v0.0.1
      with:
        # The root LaTeX file to be compiled
        root_file: manuscript.tex
        # The working directory for the LaTeX engine
        # working_directory: # optional
        # The LaTeX engine to be invoked
        compiler: latexmk # optional, default is latexmk
        # Extra arguments to be passed to the LaTeX engine
        # args: # optional, default is -pdf -file-line-error -interaction=nonstopmode
        # Install extra packages by tlmgr
        # extra_packages: # optional
        # Install extra packages by apk
        # extra_system_packages: # optional
